### PR TITLE
Rails 5 compatibility

### PR DESCRIPTION
**Pull request by glebm**
Follow-up on #69. Adds more tests and Gemfiles to test on Sprockets 2 and 3.

### CODE REVIEW

**Comment by ai** [comment]
Because of API changes I can accept this PR only in 7.0 release.

**Comment by glebm** [comment]
:+1:

**Comment by pwnall** [comment]
I'm using Rails 5 in production (crazy, I know) with Foundation for Sites 6, which uses Autoprefixer. I hard-coded a depedency on autoprefixer 6.1.0 in my Gemfile, because it has Rails 5 support, but it'd be nice to be able to use newer versions. :pray:

**Comment by glebm** [comment]
This includes #87

**Pull request closed without merging**
