### PR TITLE
Fix misnamed reference to `Runtimes` constant name

### LINKED ISSUE #141: Uninitialized constant error in templates after upgrade
Upgrading Autoprefixer from 8.6.5 to 9.1.3 yields a template error:

```
ActionView::Template::Error (uninitialized constant ExecJS::Runtimes::RubyRacerRuntime):
    11: 
    12:                 <%= content_tag :div, class: :'navbar-brand' do %>
    13:                     <%= link_to home_path do %>
    14:                         <%= image_tag 'logo.svg', height: 27 %>
    15:                     <% end %>
    16:                 <% end %>
    17: 
  app/assets/javascripts/admin/app-run.js.coffee.erb:340:in `_evaluate_template'
```

There are no upgrade instructions. Any advice?

### PR DESCRIPTION
**Pull request by chalin**
Fixes #141. /cc @kwalrath @Sfshaza @filiph

### CODE REVIEW

**Comment by ai** [comment]
Seems like it depends on ExecJS version https://github.com/sstephenson/execjs/blob/master/lib/execjs/ruby_racer_runtime.rb#L4

**Comment by ai** [comment]
I think it will be better to use `runtime.name` for detecting https://github.com/sstephenson/execjs/blob/master/lib/execjs/ruby_racer_runtime.rb#L104

Do you want to update PR?

**Comment by chalin** [comment]
Done

**Comment by ai** [comment]
I will release it on next Autoprefixer release

**Comment by ai** [comment]
Released in 9.1.4

**Pull request merged**
