### PR TITLE
Fix for issue #47

### PR DESCRIPTION
**Pull request by twalpole**
Fix to prevent error with execjs external runtimes, and test with both NodeJS and rubyracer or rubyrhino

### CODE REVIEW

**Comment by mattbrictson** [comment]
This fix works for me. Looking good! :+1:

**Comment by clemensg** [comment]
:+1:

**Comment by ai** [comment]
Awesome. Thanks for your work.

**Comment by ai** [comment]
I will release 5.0.01 right now.

**Comment by matthieua** [comment]
Thanks @ai :+1:

**Comment by CJBrew** [comment]
wow! I was just hitting this issue, and here's the fix

Thanks :+1:

**Pull request merged**
