### PR TITLE
Fix Sprockets 3.x depreciation notice

### PR DESCRIPTION
**Pull request by abeMedia**

### CODE REVIEW

**Comment by bianjp** [comment]
I think a minor release such as 6.3.8 would be quit good.

**Comment by ai** [comment]
I could release 6.3.8 only if I will release Autoprefixer.js 6.3.8.

You could use GitHub version of Autoprefixer, if you need this fix sooner.

**Comment by bianjp** [comment]
Maybe it would be a better idea to seperate the versions of `autoprefixer-rails` and `autoprefixer.js` (just like `coffee-rails` and `coffee-script`)?

**Comment by ai** [comment]
Anyway I can't do this separation in minor release 😉.

**Pull request merged**
