### PR TITLE
Fix remaining RuboCop issues

### PR DESCRIPTION
**Pull request by utkarsh2102**
Hi @ai,

This is a follow-up of #166 :rocket: 
Each commit represents a different subset of change so it'd be best to not squash those commits! :smile: 

Thanks! :heart: 

Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

### CODE REVIEW

**Comment by ai** [comment]
> it'd be best to not merge those commits

Do you mean that this PR is still in progress? You can convert it to Draft in GitHub.

**Comment by utkarsh2102** [comment]
I meant squashing, apologies! This is ready, I just did this in separate commits.
(so it'd be best if you're okay with not squashing?)

**Comment by utkarsh2102** [comment]
>  Each commit represents a different subset of change so it'd be best to not squash those commits!

~merge~ ---> squash :sweat_smile:

**Comment by ai** [comment]
Great work. Thanks :+1:

**Comment by utkarsh2102** [comment]
Thank you! :heart: 
Just last two bits are remaining now, I'll get to them at the earliest!

**Pull request merged**
