### PR TITLE
Convert from match? to match to support rubies < 2.4

### PR DESCRIPTION
**Pull request by jfo84**

### CODE REVIEW

**Comment by ai** [comment]
@jfo84 Travis CI failed:

```
standard: Use Ruby Standard Style (https://github.com/testdouble/standard)
  lib/autoprefixer-rails/processor.rb:111:12: Performance/RedundantMatch: Use `=~` in places where the `MatchData` returned by `#match` will not be used.
```

**Comment by jfo84** [comment]
@searls Is Standard not compatible with Ruby 2.3? They're actually not semantically equivalent, but using them with conditionals like this is the same behavior

**Comment by ai** [comment]
Released in 9.4.10.2.

**Comment by searls** [comment]
Yes, StandardRB supports Rubies as far back as 1.8. The issue here is I ran `standard --fix` before locking the Ruby version to 2.3 in a `.standard.yml` file, and for whatever reason the build did not catch this at the time. 

This will pass fine if Standard is run from a 2.3 ruby or if .standard.yml is set to 2.3

```ruby
if "hi" =~ /hi/
  puts "cool"
end
```

**Pull request merged**
