### PR TITLE
Use rubocop

### PR DESCRIPTION
**Pull request by utkarsh2102**
Hi @ai,

Thanks again for your awesome work in maintaining this! :fire: 

As discussed in #164, here's the first follow-up on this.
I'll do all the changes in 3 or 4 parts :)
(sorry for the delay, though!)

Signed-off-by: Utkarsh Gupta <<utkarsh@debian.org>>

### CODE REVIEW

**Comment by ai** [comment]
Too late. I just deprecate the whole Autoprefixer Rails https://github.com/ai/autoprefixer-rails/commit/b01fef4a5f1fd10301cc2e8793854f3f34497bd5

**Comment by utkarsh2102** [comment]
Woops :/
However, given that there are so many gems using this already, we will keep maintaining this in Debian for a while, at least!

It'd still be nice if you could integrate these changes :)

**Comment by utkarsh2102** [comment]
Well, in case you think it's not worth doing this anymore, I have one minor thing to change here - dropping the use of `git ls-files` in gemspec. This should really help us in maintaining. So I can instead shape this PR to do that instead?

Or in case you think, it's okay to use rubocop here, still, I can complete this whole thing.

Let me know what you think.

**Comment by ai** [comment]
Yeap, I will continue to accept security PRs.

I will accept Robocop PR a little later and I am open for gemspec PR too.

**Comment by utkarsh2102** [comment]
Okay, that's very great of you!
Thanks for your work, really! Let me know when you think it's time for merging this. Once done, I'll open another follow-up PR for RuboCop fixes and lastly for gemspec!

Thanks again! :heart:

**Pull request merged**
