### PR TITLE
Source path isn't what we want here

### PR DESCRIPTION
**Pull request by schneems**
Add a failing test for Sprockets 4 and fix

Previously sprockets 4 source maps were breaking but there was no test for them. This commit adds tests.

Reference https://github.com/rails/sprockets/pull/292#issuecomment-218786083

Fully addresses https://github.com/ai/autoprefixer-rails/pull/85#issuecomment-218786627

### CODE REVIEW

**Comment by schneems** [comment]
This functionality wasn't previously tested, which is why it wasn't failing. My previous PR lead to a bad source map.

**Comment by schneems** [comment]
cc @rafaelfranca

**Comment by rafaelfranca** [comment]
:+1:

**Comment by schneems** [comment]
Any problems with merging this?

**Comment by ai** [comment]
@schneems sorry :) the problem is 20 letters in Inbox about opensource issues :). I just finished stuff with Iran travel and CSSConf and start to fix old issues.

I am going from bottom to top. But if this issue is important to you, I can process it before others :).

**Comment by schneems** [comment]
No worries, thanks for responding quickly and letting me know your workload. The breakage was only on dev mode, it can wait a bit.

**Comment by ai** [comment]
Released in 6.3.6.1

**Comment by schneems** [comment]
Awesome! Thanks

**Comment by schneems** [comment]
Thanks again for this, curious why so many version numbers? I wrote a bit about this a while ago http://www.schneems.com/2015/11/29/what-is-semver.html

Would love to hear more about strategies you use. We can take it off this thread if you're interested i'm richard@heroku.com.

**Comment by ai** [comment]
@schneems the Autoprefixer Rails version is connected to Autoprefixer version. So I was not able to release 6.3.7 :(

RubyGems allows this non-semver version, so it works right now :). But I am open for any other solutions.

**Comment by schneems** [comment]
Ahh interesting so the first 3 numbers will always line up and the last number is used for indicating bug fixes to this repo directly. Don't think i've seen that before. It makes a lot of sense actually.

**Pull request merged**
