### PR TITLE
Improve the Gemfile for Windows

### PR DESCRIPTION
**Pull request by Dinuz**
@ai I added the gem tzinfo-data required on windows platform:)

### CODE REVIEW

**Comment by Dinuz** [comment]
@ai Ok cool!
Did you see my other message? the one with all the tests?

**Comment by ai** [comment]
A saw and accept your PR

**Comment by ai** [comment]
Yeap, I am reading it right now

**Comment by Dinuz** [comment]
lol no I meant this:
https://github.com/ai/autoprefixer-rails/commit/45853d9423e97c7c1cf1741a909f79774410494d

**Comment by Dinuz** [comment]
@ai Cool!

**Comment by ai** [comment]
@Dinuz tests fails on Windows because Ruby can’t create a shell. I think it is not a big problem right now (Travis CI anyway have no full Windows support as I know).

But if you will fix this errors, I will be happy.

**Comment by Dinuz** [comment]
@ai it's not an issue, the gem works fine now.
I am going to look into it and see what I can do:)

**Comment by ai** [comment]
Problem is about:

```ruby
`cd path; ./binary`
```

statement.

Here is a bad lines: [compass_spec](https://github.com/ai/autoprefixer-rails/blob/master/spec/compass_spec.rb#L13), [rails_spec](https://github.com/ai/autoprefixer-rails/blob/master/spec/rails_spec.rb#L25).

Maybe we need use some other method instead of `. But I have no experience here.

**Comment by Dinuz** [comment]
@ai give me few days and I will look into it during the we. ok?

**Comment by ai** [comment]
np :)

**Pull request merged**
