### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds a GitHub Actions configuration YAML.

## Details

Drops Travis CI configuration file and badge. 

I borrowed this one: https://boringrails.com/articles/building-a-rails-ci-pipeline-with-github-actions/ 

## TODO

Add builds which do this:

- [x] "EXECJS_RUNTIME=Node" for Ruby 2.7
- [x] "EXECJS_RUNTIME=MiniRacer" for all combinations

---

When I was done, I found: https://docs.github.com/en/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

### CODE REVIEW

**Comment by olleolleolle** [comment]
@albb0920 I am guessing that you, the project maintainer, needs to enable something for this to be replace the other CI. I will drop Travis details in this PR, too.

**Comment by albb0920** [comment]
Do you have a repo demonstrate this working?
I've checked yours, it seems to have some issues.
https://github.com/olleolleolle/autoprefixer-rails/actions/workflows/ci.yml

**Comment by olleolleolle** [comment]
@albb0920 Thanks for the hint, I'll return when I've learned more!

**Comment by olleolleolle** [comment]
@albb0920 OK, seems like it's going better now.

bild

**Comment by mishina2228** [comment]
Hi @albb0920, how is it going?
travis-ci.org is already ceased, so we'd like to migrate to GitHub Actions.

I ran the CI in my forked repo, and it is mostly green.
https://github.com/mishina2228/autoprefixer-rails/actions/runs/1703649823
Tests(macos-latest, 2.6) is failing now, but this is caused by the following issue in mini_racer: https://github.com/rubyjs/mini_racer/issues/223
I'm hoping this issue will be resolved in the near future, so would you consider merging this PR?
Thank you!

**Comment by albb0920** [comment]
Sorry for the delay, I’ll have a look in a few days

2022年1月16日(日) 20:43 mishina2228 ***@***.***>:

**Comment by mishina2228** [comment]
Thanks!
And now that the mini_racer issue has been fixed, all CIs are green!

**Comment by olleolleolle** [comment]
@mishina2228 Anything else you need from me, here? Glad they're green.

**Comment by mishina2228** [comment]
@olleolleolle Nothing special, but maybe add CI against Ruby 3.1?😆

**Comment by albb0920** [comment]
Sorry for the very long delay.
Rebased & merged, thank you!

**Pull request closed without merging**
